[build]
  functions = "functions"

[dev]
  command = "node app.js"  # For local development
  targetPort = 3000          # Port your Express app runs on

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/express-app"
  status = 200
